### ISSUE TITLE
Error when running packaged mount-safe-linux (mock)

### ISSUE THREAD

**Issue by happybeing** [theWebalyst/safenetwork-fuse#1]
safenetwork-fuse v0.0.2  works with mock SAFE Browser. The following auths with mock browser and then mounts a simulated filesystem at ~/SAFE
```
export NODE_ENV=dev
node bin.js
```

Then, in another terminal:
```
$ cd ~/
$ ls -l SAFE
total 0
drwxr-xr-x 1 mrh mrh 1234 Jun 12 21:41 one
-rw-r--r-- 1 mrh mrh 1234 Jun 12 21:41 three
-rw-r--r-- 1 mrh mrh 1234 Jun 12 21:41 two
$ tree SAFE
SAFE
├── one
│   ├── five
│   ├── four
│   └── happybeing
├── three
└── two

1 directory, 5 files
$ sudo umount ~/SAFE
```

I then package this for Windows, Mac and Linux:

```
npm run buildall-mock
$ npm run buildall-mock

> safenetwork-fuse@0.0.2 buildall-mock /home/mrh/src/fuse/safenetwork-fuse
> mkdir -p ./dist/mock/node_modules/@maidsafe/safe-node-app/src/native/mock/ && cp -R node_modules/@maidsafe/safe-node-app/src/native/mock/*.* ./dist/mock/node_modules/@maidsafe/safe-node-app/src/native/mock/ && pkg -t linux,macos,win -o ./dist/mock/mount-safe bin.js

> pkg@4.3.1
```

But the built command fails:
```
$ ./dist/mock/mount-safe-linux
pkg/prelude/bootstrap.js:1172
      throw error;
      ^

Error: No native build was found for runtime=node abi=57 platform=linux arch=x64
    at Function.load.path (/snapshot/safenetwork-fuse/node_modules/node-gyp-build/index.js:31:9)
    at load (/snapshot/safenetwork-fuse/node_modules/node-gyp-build/index.js:13:23)
    at Object.<anonymous> (/snapshot/safenetwork-fuse/node_modules/fuse-bindings/index.js:1:99)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:644:10)
    at Module.load (module.js:552:32)
    at tryModuleLoad (module.js:495:12)
    at Function.Module._load (module.js:487:3)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
```

**Comment by happybeing** [comment]
I've tracked the problem down to `node-gyp-build/index.js` which is used by fuse-bindings to load native builds. In the above error message it is looking for `fuse-bindings/prebuilds/linux-x64/node-57.node` which is present in the packaged 'snapshot'.

The problem is that inside `fs.readdirSync(dir)` doesn't work even though the files are present:

https://github.com/mafintosh/node-gyp-build/blob/master/index.js#L34-L41

I showed this is the case by adding the following line just above `throw new Error('No native build...`

`return '/snapshot/safenetwork-fuse/node_modules/fuse-bindings/prebuilds/linux-x64/node-57.node'`

**Comment by happybeing** [comment]
So how to fix `node-gyp-build/index.js` so it can find the prebuilds?

**Comment by happybeing** [comment]
I can make a build that works by:
- package.json assets, add: "node_modules/fuse-bindings/prebuilds/**/*.*" 
- package.json scripts, change pkg build commands to pass '.' instead of 'bin.js'
  -> this results in a larger executable file (112MB compared to 48MB) and a lot of warnings from `pkg` as follows:
```
	> Warning Cannot include addon %1 into executable.
	  The addon must be distributed with executable as %2.
	  /home/mrh/src/fuse/safenetwork-fuse/node_modules/fuse-bindings/prebuilds/linux-x64/node-57.node
	  path-to-executable/node-57.node
```

The resulting executable works fine (only Linux tested).

Note, currently even the packaged executable needs a copy of `node_modules/@maidsafe/safe-node-app` next to the executable.

**Comment by bm371613** [comment]
I get this error using the latest release

```
bartek@bartek-pc ~/Pobrane/safenetwork-fuse-v0.1.0-linux-x64
$ ./mount-safe 
pkg/prelude/bootstrap.js:1176
      throw error;
      ^

Error: Could not locate the bindings file. Tried:
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/build/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/build/Debug/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/build/Release/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/out/Debug/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/Debug/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/out/Release/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/Release/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/build/default/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/compiled/8.11.3/linux/x64/weakref.node
    at bindings (/snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/lib/weak.js:7:35)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (module.js:661:10)
    at Module.load (module.js:563:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:594:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/module.js:11:18)
```

**Comment by happybeing** [comment]
Thanks @bm371613 we've seen this too so working on it. It is a different issue though so I've opened a new issue #3

**Comment by happybeing** [comment]
Update for anyone seeing this kind of issue on Linux, please check the [dependencies](https://github.com/theWebalyst/safenetwork-fuse#31-linux) against your distro.

**Comment by happybeing** [comment]
Closing in favour of [issue #3](https://github.com/theWebalyst/safe-drive/issues/3) in [new SAFE Drive repo](https://github.com/theWebalyst/safe-drive) as this repo is no longer in use.
